# Generated by Django 3.1.9 on 2022-02-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_transactions_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product2', to='app1.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product3', to='app1.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product4', to='app1.product'),
        ),
    ]
